/* 首页「今天」数据：365 条双语每日一句 + 趣味黄历宜忌清单
 * 句子按一年中的第几天轮换（DAILY_SENTENCES[dayOfYear % 365]）。
 * 宜忌为趣味随机（每天固定），非正统黄历。
 */

const DAILY_SENTENCES = [
  ["早餐吃得好，一整天都有底气 🍳","A good breakfast carries me through the day"],
  ["先把豆浆喝热，再慢慢对付生活","Warm soy milk first, then life can wait"],
  ["一碗白粥配咸菜，也是踏实的幸福","Plain congee with pickles is quiet happiness"],
  ["早安从一口煎蛋开始，简单却满足 🍳","Morning begins with a fried egg, simple and satisfying"],
  ["别饿着肚子赶路，早餐值得认真对待","Never rush through the day on an empty stomach"],
  ["今天的包子冒着热气，日子也冒着热气 🥟","Steaming buns, steaming days, both full of life"],
  ["烤一片吐司，把清晨烤得香喷喷","Toast a slice and make the morning smell good"],
  ["牛奶加麦片，给新的一天充个电 🥛","Milk and cereal to charge up a brand new day"],
  ["人间烟火气，最抚凡人心，先从早餐起","The smell of breakfast is the kindest comfort"],
  ["再忙也要坐下来，把早饭慢慢吃完 🥣","However busy, sit down and finish breakfast slowly"],
  ["一碗热汤面下肚，浑身都舒坦了","A bowl of hot noodle soup warms me all over"],
  ["面条要趁热嗦，日子要趁热过","Slurp the noodles hot, live the days warm"],
  ["深夜那碗面，是给自己的温柔安慰 🍜","Late-night noodles are my own gentle comfort"],
  ["小葱拌豆腐配碗面，清淡也有滋味","Simple noodles with tofu still taste like plenty"],
  ["下雨天就该吃面，咕噜咕噜喝光汤","Rainy days are made for noodles and hot broth"],
  ["手擀面里有耐心，吃进嘴里都是诚意","Hand-pulled noodles carry patience in every bite"],
  ["饿的时候来碗面，世界立刻讲道理了 🍜","One bowl of noodles and the world makes sense"],
  ["番茄鸡蛋面，是永远不会出错的选择","Tomato-egg noodles never let me down"],
  ["把烦恼拌进面里，一口一口吃掉它 🥢","Mix your worries into the noodles and eat them"],
  ["凉面配黄瓜丝，夏天的快乐很简单","Cold noodles with cucumber: summer's simple joy"],
  ["火锅一沸腾，烦恼就退场了 🍲","Once the hotpot bubbles, worries leave the room"],
  ["没有什么事是一顿火锅解决不了的","If anything can fix it, hotpot can"],
  ["毛肚七上八下，快乐刚刚好 🥘","Seven dips of tripe, just the right amount of joy"],
  ["约上三五好友，围炉涮出好心情","Gather friends around the pot and simmer some joy"],
  ["冬天就是要吃火锅，从胃暖到心 ❄️","Winter means hotpot, warming from stomach to heart"],
  ["麻辣锅配冰粉，辣得痛快甜得及时","Spicy broth with icy jelly, burn then soothe"],
  ["一个人吃小火锅，也要涮得热气腾腾","Solo hotpot still deserves a full rolling boil"],
  ["蘸料是火锅的灵魂，我的秘方不外传 🥣","The dipping sauce is hotpot's soul, mine stays secret"],
  ["涮一片肥牛，把疲惫都涮走了","One slice of beef and the fatigue melts away"],
  ["火锅店里的人声，是最下饭的伴奏 🍲","The chatter in a hotpot place seasons the meal"],
  ["奶茶三分糖，快乐不打烊 🧋","Milk tea with light sugar keeps the joy flowing"],
  ["今天的慰藉，是一杯温热的珍珠奶茶","Today's comfort is a warm cup of boba"],
  ["吸一口珍珠，嚼出小小的幸福感","Chew the pearls, taste the little happiness"],
  ["奶茶可以不用喝，但快乐一定要续杯","Skip the tea if you must, never skip the joy"],
  ["下午茶时间到，给自己一点甜 🍰","Afternoon tea o'clock, a little sweetness for me"],
  ["手捧一杯热可可，连心都软乎乎","Hands around hot cocoa, heart gone soft"],
  ["买杯果茶逛逛街，日子慢悠悠 🍹","Fruit tea in hand, strolling through a slow day"],
  ["这一杯敬自己，辛苦了也值得甜一下","This cup is a toast to me, tired but deserving"],
  ["热饮暖手，甜味暖心，正好","Warm cup for the hands, sweetness for the heart"],
  ["奶茶虽好，也要记得多喝水哦","Milk tea is great, but water still counts"],
  ["饭后来个苹果，清甜又解腻","An apple after dinner, crisp and refreshing"],
  ["夏天的西瓜最中间那勺，要留给自己 🍉","The sweetest spoonful of watermelon is mine"],
  ["草莓季到了，把春天吃进嘴里 🍓","Strawberry season means tasting spring itself"],
  ["剥个橘子慢慢吃，让时间也慢下来 🍊","Peel an orange slowly and let time slow down"],
  ["水果切好摆盘，生活就有了仪式感","Sliced fruit on a plate makes life feel ceremonial"],
  ["一根香蕉一杯奶，懒人也有健康早餐","A banana and milk: the lazy person's healthy start"],
  ["葡萄一颗颗吃，快乐一点点攒 🍇","Grape by grape, I save up tiny joys"],
  ["饭后水果不能少，这是生活的小规矩","Fruit after meals is my little house rule"],
  ["猕猴桃酸酸甜甜，像极了日子的味道","Sweet-sour kiwi tastes just like life itself"],
  ["多吃水果多喝水，皮肤和好天气一起变好","More fruit, more water, better skin and better days"],
  ["蛋糕不必等生日，想吃就是好日子 🎂","Cake needs no birthday; craving is reason enough"],
  ["一块提拉米苏，把下午变得温柔","One tiramisu makes the whole afternoon tender"],
  ["刚出炉的蛋挞，酥皮里藏着小太阳 🥧","Fresh egg tarts hide little suns in their crusts"],
  ["冰淇淋第一口，永远是幸福的形状 🍦","The first bite of ice cream is shaped like happiness"],
  ["心情不好就吃块巧克力，甜能治愈大半 🍫","A piece of chocolate fixes most bad moods"],
  ["双皮奶滑进嘴里，烦恼滑出心外","Silky milk pudding slides the worries away"],
  ["烤一盘小饼干，满屋子都是香甜 🍪","Bake some cookies and perfume the whole house"],
  ["布丁摇摇晃晃，快乐也跟着晃 🍮","The pudding wobbles and so does my joy"],
  ["偶尔吃点甜的，是对自己的奖励","A little sweetness now and then is self-respect"],
  ["糖水铺子坐一坐，把时光熬得稠稠的","Sit in a dessert shop and let time thicken"],
  ["家常菜的香，是外面买不到的味道 🍚","Home cooking has a flavor no restaurant sells"],
  ["妈妈做的红烧肉，一口回到小时候","Mom's braised pork takes me straight back home"],
  ["一荤一素一碗汤，就是最安心的晚餐 🍲","Meat, greens, and soup: the most reassuring dinner"],
  ["厨房飘着饭香，家就有了样子","When the kitchen smells of dinner, home feels real"],
  ["番茄炒蛋拌米饭，怎么都吃不腻 🍅","Tomato-egg over rice never gets old"],
  ["自己下厨做顿饭，成就感比外卖香","Cooking at home tastes better than any delivery"],
  ["砂锅咕嘟咕嘟，炖的是日子的耐心 🍲","The clay pot bubbles with the patience of days"],
  ["清炒时蔬也下饭，平淡里见真味 🥬","Simple stir-fried greens reveal true flavor"],
  ["周末煲一锅汤，犒劳辛苦一周的自己 🍲","Weekend soup rewards a week of hard work"],
  ["剩饭做成蛋炒饭，照样香喷喷","Leftover rice becomes glorious fried rice"],
  ["好好吃饭，是对生活最基本的尊重 🍚","Eating well is the basic respect we owe life"],
  ["一日三餐按时吃，就是稳稳的幸福","Three meals on time is steady happiness"],
  ["先把饭吃好，再谈诗和远方 🍜","Eat well first, then chase poetry and distance"],
  ["别拿泡面凑合，你值得一顿正经饭","Don't settle for instant noodles; you deserve a real meal"],
  ["认真吃饭的人，运气都不会太差 🥢","People who eat with care rarely run out of luck"],
  ["再忙也要记得，胃饱了心才不慌","However busy, a full stomach steadies the heart"],
  ["吃饭不看手机，好好尝尝每一口 📵","No phone at the table; taste every bite"],
  ["把每一餐都当回事，日子就不会将就","Take every meal seriously and life won't settle"],
  ["今天的胃，也要被温柔地填满 🍚","Today's stomach deserves to be gently filled"],
  ["好好吃饭好好睡觉，平凡就是答案","Eat well, sleep well; the ordinary is the answer"],
  ["早餐铺子的烟火，是城市最早的温柔 🥟","The breakfast stall's steam is the city's first kindness"],
  ["一碗馄饨下肚，夜里不再冷清 🥟","A bowl of wontons keeps the night from feeling cold"],
  ["烧烤配晚风，夏天的夜晚刚刚好 🍢","Skewers and evening breeze make a perfect summer night"],
  ["路边摊的炒粉，藏着最接地气的快乐","Street-stall fried noodles hold the truest joy"],
  ["热腾腾的包子铺，叫醒整条老街 🥟","The steaming bun shop wakes the whole old street"],
  ["夜宵不必丰盛，热乎就行 🌙","Late-night food need not be fancy, just warm"],
  ["豆浆油条的早晨，烦恼还没上班","Soy milk and dough sticks, before worries clock in"],
  ["一锅白米饭的香气，最能安慰疲惫 🍚","The smell of steaming rice consoles a tired day"],
  ["吃饱了才有力气，继续热爱生活","Only a full belly has the strength to love life"],
  ["细嚼慢咽，把日子过出味道来 🥢","Chew slowly and savor the flavor of the days"],
  ["冰箱里常备酸奶和水果，安全感拉满 🥛","Yogurt and fruit in the fridge mean security"],
  ["炖一锅排骨玉米汤，全家都暖和 🌽","A pot of pork and corn soup warms everyone"],
  ["春风一吹，连走路都想哼小曲儿 🌸","Spring breeze makes me hum while I walk"],
  ["去楼下看看，玉兰花是不是偷偷开了","Checking if the magnolias bloomed overnight"],
  ["春天适合发呆，也适合重新出发","Spring is for daydreaming and fresh starts"],
  ["把冬天的厚外套收好，轻装上阵啦 🌱","Packing away my winter coat, feeling light"],
  ["樱花落得慢一点吧，我还没看够呢","Fall slower, cherry blossoms, I'm not done looking"],
  ["小草都冒芽了，我也该振作起来了 🌿","The grass is sprouting, so should I"],
  ["春雨细细的，落在脸上凉凉的","Spring drizzle feels cool and soft on my face"],
  ["趁着春光正好，去公园坐一会儿吧 ☀️","Let's sit in the park while spring sunshine lasts"],
  ["风里都是花香，忍不住多吸两口","The wind smells like flowers, I keep breathing it in"],
  ["春天快乐，愿你像小树一样蹭蹭长高 🌷","Happy spring, may you grow like a little tree"],
  ["不用赶路的季节，慢慢走就是风景 🍃","No rushing in spring, slow walking is the view"],
  ["夏天是从第一口冰西瓜开始的 🍉","Summer begins with the first bite of cold watermelon"],
  ["午后下了一场雷阵雨，痛快极了","An afternoon thunderstorm, loud and wonderful"],
  ["蝉鸣吵是吵了点，但很有夏天的感觉","Cicadas are noisy, but that's the sound of summer"],
  ["傍晚的风终于凉了，出门散个步吧 🌆","Evening breeze finally cooled, time for a walk"],
  ["夏天就要大汗淋漓，然后冲个凉","Sweat it out in summer, then take a cool shower"],
  ["晚霞把天烧红了，赶紧拍一张 📷","The sunset set the sky on fire, grabbed a photo"],
  ["冰汽水的气泡声，是夏天的背景音乐 🥤","Soda bubbles are the soundtrack of summer"],
  ["大朵大朵的白云，像棉花糖飘在天上 ☁️","Summer clouds float like giant cotton candy"],
  ["夜风习习，搬个凳子到楼下乘凉吧","Cool night breeze, bring a stool downstairs"],
  ["一场秋雨一场凉，记得添件衣裳 🍂","Each autumn rain brings chill, add a layer"],
  ["秋天是桂花味儿的，走到哪香到哪","Autumn smells like osmanthus everywhere I go"],
  ["踩踩落叶，听听那咔嚓咔嚓的声音 🍁","Stepping on fallen leaves, crunch crunch crunch"],
  ["天高云淡的日子，心情也跟着敞亮","High skies and thin clouds lift my mood"],
  ["秋天适合吃点热乎的，比如糖炒栗子 🌰","Autumn calls for warm roasted chestnuts"],
  ["银杏叶黄了，铺了一地的金子","Ginkgo leaves turned the ground into gold"],
  ["秋风一起，就想裹紧外套慢慢走 🧥","Autumn wind makes me hug my coat and stroll"],
  ["捡一片好看的叶子，夹进书里当书签","A pretty leaf becomes my new bookmark"],
  ["阳光不烫人的季节，晒着刚刚好 ☀️","Autumn sunshine is warm but never too much"],
  ["柿子红了，秋天就算真正到了","Persimmons turning red means autumn has arrived"],
  ["冬天哈出的白气，是免费的棉花糖 ❄️","My winter breath makes free cotton candy"],
  ["冷归冷，热乎乎的烤红薯不能少 🍠","Cold as it is, I need my roasted sweet potato"],
  ["最幸福的事，是钻进晒过太阳的被窝","Best of winter: a sun-warmed blanket at night"],
  ["裹成粽子出门，也是对冬天的尊重 🧣","Bundled up like a dumpling, respecting winter"],
  ["天冷了，更要好好吃饭好好睡觉","Cold days mean eating and sleeping extra well"],
  ["冬天的太阳像个宝贝，出来就赶紧晒 🌞","Winter sun is treasure, catch it while it shines"],
  ["手脚冰凉的季节，记得给自己泡杯热茶 ☕","Cold hands and feet deserve a cup of hot tea"],
  ["冬夜再长，天亮之后又是新的一天","Long winter nights still end in a new morning"],
  ["盼一场雪，把这个冬天盖得软软的","Waiting for snow to tuck this winter in"],
  ["下雨了，听着雨声赖会儿床也不错 🌧️","Rainy day, staying in bed to the sound of rain"],
  ["雨点打在窗户上，像在给我弹曲子","Raindrops on the window play me a little tune"],
  ["雨后的空气是甜的，深呼吸一下 🌈","The air after rain tastes sweet, breathe deep"],
  ["出门记得带伞，别淋成落汤鸡啦","Bring an umbrella, don't get soaked out there"],
  ["下雨天和热汤面最配，暖到心里 🍜","Rainy days and hot noodle soup warm the heart"],
  ["踩水坑这件小事，长大了也想试试 💦","Splashing puddles still tempts the grown-up me"],
  ["雨停啦，地上的水洼映着一小片天","Rain stopped, puddles holding little pieces of sky"],
  ["喜欢雨声，像有人轻轻拍着我说晚安","Rain sounds like a gentle pat saying goodnight"],
  ["大晴天，把被子抱出去晒晒吧 ☀️","Sunny day, time to air out the blankets"],
  ["太阳一出来，什么烦恼都晒没了","Sunshine dries up all my little worries"],
  ["晴天的影子又黑又清晰，踩着玩 😄","Sharp shadows on sunny days, fun to step on"],
  ["阳光透过树叶洒下来，晃得人眯起眼 🌳","Sunlight through the leaves makes me squint happily"],
  ["今天的天空蓝得很认真，值得抬头看","Today's sky is seriously blue, look up"],
  ["风吹过来的时候，烦恼好像轻了一点 🍃","When the wind blows, worries feel lighter"],
  ["大风天出门，头发有自己的想法 💨","Windy day out, my hair has its own plans"],
  ["晚风不冷不热，正适合压马路","The evening breeze is perfect for a stroll"],
  ["风把云吹得飞快，像在赶时间的样子","Wind hurries the clouds across the sky"],
  ["站在风里张开手，假装自己在飞","Arms open in the wind, pretending to fly"],
  ["听，风穿过树叶的声音，沙沙沙 🌿","Listen to the wind rustling through the leaves"],
  ["下雪啦下雪啦，快开窗看看 ❄️","It's snowing, quick, open the window"],
  ["雪落在手心里，一秒钟就化了","A snowflake melts in my palm in a second"],
  ["雪后的世界安安静静的，像按了静音键 ⛄","The world after snow is on mute"],
  ["在雪地里踩出第一串脚印，成就感满满","First footprints in fresh snow, so satisfying"],
  ["早起看日出，困是困了点，但值了 🌅","Waking early for sunrise, sleepy but worth it"],
  ["太阳一点点冒头，天边慢慢变橙","The sun peeks up, the horizon turns orange"],
  ["新的一天从第一缕阳光开始，加油呀 ☀️","A new day starts with the first sunlight, go"],
  ["日落不等人，想看的风景要趁早","Sunsets wait for no one, go see them early"],
  ["下班路上撞见晚霞，一天的疲惫都值了 🌇","Sunset glow on the way home heals the whole day"],
  ["日头落山前，天空把颜色都用了一遍","Before dark, the sky uses up every color"],
  ["看太阳慢慢落下去，心也跟着静下来","Watching the sun sink slows my heart down"],
  ["黄昏的光软软的，照什么都好看 🌆","Dusk light is soft and makes everything lovely"],
  ["天上的云今天像只大绵羊，你看像不像 ☁️","That cloud looks like a giant sheep, right"],
  ["云飘得那么慢，是在教我别着急","Clouds drift slowly, teaching me patience"],
  ["躺在草地上看云，一看就是一下午","Lying on the grass, watching clouds all afternoon"],
  ["乌云来啦，快跑，雨马上就到 🌥️","Dark clouds coming, run before the rain"],
  ["云朵是天空写的情书，每天都要读","Clouds are love letters the sky writes daily"],
  ["今晚的月亮好圆，像个大灯泡挂在天上 🌕","Tonight's moon hangs like a big round bulb"],
  ["抬头看看月亮吧，再忙也别忘了 🌙","Look up at the moon, no matter how busy"],
  ["星星不多，但每一颗都在认真眨眼 ✨","Few stars tonight, but each one twinkles hard"],
  ["月亮跟着我走，走到家它也到家了","The moon walks me home and arrives with me"],
  ["夜空中最亮的那颗星，我先许愿啦","The brightest star gets my first wish tonight"],
  ["月牙弯弯，像天空在对我微笑","The crescent moon is the sky smiling at me"],
  ["楼下的花开了，记得去跟它打个招呼 🌼","Flowers bloomed downstairs, go say hi"],
  ["给阳台的绿植浇浇水，跟它们聊聊天 🪴","Watering my plants and chatting with them"],
  ["大树底下好乘凉，老话说得真没错","Shade under big trees, the old saying holds"],
  ["花开有时，别着急，慢慢来","Flowers bloom in season, no need to hurry"],
  ["路边的蒲公英，许个愿再吹散它","Make a wish before blowing the dandelion"],
  ["树叶绿得发亮，夏天藏不住了 🍀","Leaves shining green, summer can't hide anymore"],
  ["饭后百步走，活到九十九，走走走 🚶","A walk after dinner keeps the doctor away"],
  ["散步不设目的地，走到哪算哪","Walking with no destination, wherever I end up"],
  ["今天的天空很好看，记得抬头 🌤️","The sky looks great today, remember to look up"],
  ["沿着河边慢慢走，水声听着真舒服","Strolling by the river, the water sounds lovely"],
  ["散个步出出汗，烦恼跟着汗水溜走了 💧","A sweaty walk lets worries slip away"],
  ["累了就停下来歇一会儿，没什么大不了的 🌿","It's okay to rest when you're tired."],
  ["慢慢来，好戏都在后头呢 ☕","Take your time; the best is yet to come."],
  ["今天的你，已经做得很棒了 👏","You've done really well today."],
  ["别焦虑，事情总会一件件解决的","Don't worry; things will work out one by one."],
  ["小小的进步，也值得被认真庆祝 🎈","Small progress deserves a real celebration."],
  ["先抱抱自己，再继续往前走吧","Give yourself a hug, then keep going."],
  ["元气满满的一天，从微笑开始 😊","A bright day starts with a smile."],
  ["允许自己偶尔偷个懒，真的没关系","It's fine to be lazy once in a while."],
  ["心情低落的时候，就去晒晒太阳吧 ☀️","When you feel down, go soak up some sun."],
  ["走得慢没关系，只要别停下脚步 🐢","Slow is fine, as long as you keep moving."],
  ["给自己泡杯热茶，烦恼先放一边","Make yourself tea and set worries aside."],
  ["你已经很努力了，别对自己太苛刻","You've worked hard enough; go easy on yourself."],
  ["难过就哭一场，哭完又是新的一天","Cry it out; tomorrow is a fresh start."],
  ["每个认真生活的人，都值得被温柔以待 🌷","Everyone who lives earnestly deserves gentleness."],
  ["别急，属于你的花期总会到来 🌸","No rush; your season to bloom will come."],
  ["把坏情绪交给晚风，明天又是好天气 🌙","Hand your bad mood to the night breeze."],
  ["允许一切慢慢来，包括你自己","Allow everything to take time, including yourself."],
  ["今天也要记得夸一夸努力的自己 🌟","Remember to praise your hardworking self today."],
  ["休息一下不是认输，是给自己充电 🔋","Resting isn't giving up; it's recharging."],
  ["生活不会一直难，熬过去就是晴天","Life won't stay hard forever; clear skies ahead."],
  ["做不完的明天再说，今晚先好好睡 😴","Leave what's undone for tomorrow; sleep well tonight."],
  ["我允许自己不完美，也允许自己开心","I allow myself to be imperfect and happy."],
  ["一步一脚印，走得慢也很帅","Step by step, slow walking is still cool."],
  ["先把心情照顾好，事情自然顺起来","Care for your mood first, and things will follow."],
  ["焦虑解决不了问题，深呼吸试试看 🌬️","Anxiety solves nothing; try a deep breath."],
  ["你比自己想象中，要坚强得多 💪","You're much stronger than you think."],
  ["累了就靠一会儿，肩膀借给自己","Lean on yourself a while when you're tired."],
  ["今天的小进步，是明天的大惊喜 ✨","Today's small step is tomorrow's big surprise."],
  ["别忘了，你也是值得被爱的人 ❤️","Don't forget, you deserve to be loved too."],
  ["慢慢来比较快，急什么呢","Slow and steady gets there faster; why rush?"],
  ["把烦心事写下来，然后统统丢掉 📝","Write your worries down, then toss them away."],
  ["元气不足的时候，就吃点好吃的 🍰","When energy runs low, treat yourself to something tasty."],
  ["我很好，我只是需要一点点时间","I'm fine; I just need a little time."],
  ["给自己一个拥抱，说声辛苦了 🤗","Give yourself a hug and say well done."],
  ["阴天总会过去，太阳一直都在","Cloudy days pass; the sun is always there."],
  ["不必和别人比，你只负责超越自己","No need to compare; just outdo yesterday's you."],
  ["深呼吸三次，世界就没那么可怕了","Three deep breaths, and the world feels safer."],
  ["今天不开心也没关系，明天再开心 😌","It's okay to feel off today; smile tomorrow."],
  ["好好吃饭好好睡觉，就是最大的自律 🍚","Eating and sleeping well is the best discipline."],
  ["我走的每一步，都算数","Every step I take counts."],
  ["别对自己失望，你一直在进步呀 🌱","Don't be disappointed; you're always growing."],
  ["心累了，就去看看喜欢的风景吧 🌄","When your heart is tired, go see a view you love."],
  ["凡事尽力就好，剩下的交给时间","Just do your best; leave the rest to time."],
  ["我值得所有温柔，包括自己的那份","I deserve all tenderness, including my own."],
  ["慢一点没关系，别把自己弄丢了 🍃","Slow down; just don't lose yourself."],
  ["不开心就吃顿好的，烦恼减半 🍲","A good meal cuts your worries in half."],
  ["今天的烦恼，不带到明天的梦里","Leave today's worries out of tomorrow's dreams."],
  ["我已经很棒了，真的不用怀疑","I'm already great; no need to doubt it."],
  ["把期待放低一点，快乐就多一点 🍀","Lower expectations a little, gain more joy."],
  ["允许自己慢下来，生活不是赛跑","Allow yourself to slow down; life isn't a race."],
  ["心情下雨天，记得给自己撑把伞 ☂️","On rainy mood days, hold an umbrella for yourself."],
  ["别怕，天塌下来还有高个子顶着呢","Don't be afraid; someone taller holds up the sky."],
  ["好好爱自己，是终身浪漫的开始 💐","Loving yourself is the start of lifelong romance."],
  ["我走的慢，但我从不后退","I walk slowly, but I never walk backward."],
  ["烦恼就像乌云，风一吹就散了 🌤️","Worries are clouds; one breeze blows them away."],
  ["先把今天过好，明天自有安排","Live today well; tomorrow will arrange itself."],
  ["累了就抱抱枕头，世界明天再说 🛌","Hug your pillow; the world can wait till tomorrow."],
  ["我的节奏我做主，谁也别催","My pace, my rules; nobody gets to rush me."],
  ["一点点变好，就是很了不起的成就 🏅","Getting a little better is a real achievement."],
  ["别让坏情绪，偷走你的好胃口","Don't let bad moods steal your good appetite."],
  ["我原谅今天的自己，明天继续加油","I forgive today's me and push on tomorrow."],
  ["心里种花，日子才不会荒芜 🌻","Plant flowers in your heart and days won't go barren."],
  ["先照顾情绪，再处理事情","Tend to your feelings before tackling tasks."],
  ["今天没做好的，明天还有机会呀 🌈","What you missed today, you can try again tomorrow."],
  ["我可以不完美，但我要很快乐","I don't need perfection; I do need happiness."],
  ["把委屈说给月亮听，说完就翻篇 🌝","Tell the moon your grievances, then turn the page."],
  ["我慢慢来，反正日子还长着呢","I'll take it slow; there's plenty of road ahead."],
  ["努力之余，别忘了犒劳一下自己 🎁","Between efforts, remember to reward yourself."],
  ["心软一点没关系，对自己也是","It's okay to be soft, especially with yourself."],
  ["今天的我，比昨天更懂得爱自己了 💖","Today I love myself a little more than yesterday."],
  ["别急别怕，一切都会好起来的","No rush, no fear; everything will be fine."],
  ["难过时记得，你并不是一个人 🫂","When sad, remember you're not alone."],
  ["我允许生活有裂缝，光才照得进来","I allow cracks in life; that's how light gets in."],
  ["睡个好觉，就是对自己最好的温柔","A good night's sleep is the kindest self-care."],
  ["不完美的日子，也值得认真过","Imperfect days still deserve to be lived well."],
  ["我把烦恼折成纸飞机，扔出窗外 ✈️","I fold worries into paper planes and toss them out."],
  ["先让自己开心，其他的往后排","Make yourself happy first; the rest can wait."],
  ["我很好，而且会越来越好 🚀","I'm good, and getting better every day."],
  ["别慌，你已经在正确的路上了 🧭","Don't panic; you're already on the right path."],
  ["累的时候，想想已经走了多远","When tired, remember how far you've come."],
  ["我把今天的疲惫，交给今晚的月亮 🌛","I hand today's tiredness to tonight's moon."],
  ["微笑不用花钱，却能治愈一整天","A smile costs nothing but heals the whole day."],
  ["我按自己的节奏，慢慢盛开就好 🌺","I'll bloom slowly, at my own pace."],
  ["偶尔摆烂一下，天不会塌的","Slacking off once in a while won't end the world."],
  ["今天的眼泪，会变成明天的力量 💧","Today's tears become tomorrow's strength."],
  ["我把目标切小一点，快乐就近一点","Smaller goals bring happiness closer."],
  ["心里有光的人，走到哪都不怕 🔦","With light in your heart, nowhere is scary."],
  ["我不用很厉害，舒服自在就好","I don't need to be impressive; comfortable is enough."],
  ["把日子过成诗，先从不焦虑开始","Make life poetic, starting with less anxiety."],
  ["我给自己打打气，明天继续冲呀 🎉","I cheer myself on; tomorrow we go again."],
  ["风雨之后，记得奖励勇敢的自己 🍫","After the storm, reward your brave self."],
  ["此刻的我，就是最好的我","Right now, I am the best version of me."],
  ["周末的早晨，让我再赖五分钟床 🛏️","Let me snooze five more minutes this weekend morning"],
  ["被窝太舒服了，今天允许自己多躺一会儿","The bed is too cozy; extra lounging allowed today"],
  ["睡到自然醒，是对周末最基本的尊重 😴","Sleeping in naturally is basic weekend respect"],
  ["今晚早点睡，明天的自己会感谢我 🌙","Sleep early tonight; tomorrow's me will be grateful"],
  ["把手机放下，是时候和枕头约会了","Phone down, time for a date with my pillow"],
  ["好好睡一觉，烦恼明天再说 💤","Sleep well; worries can wait until tomorrow"],
  ["睡前不刷手机，今晚做个好梦","No scrolling before bed, sweet dreams tonight"],
  ["午休二十分钟，下午元气满满","A twenty-minute nap recharges my whole afternoon"],
  ["失眠的夜里，数羊不如数开心的事 🐑","When I can't sleep, I count happy things instead"],
  ["早睡一次，感觉赚到了一整天","One early night feels like gaining a whole day"],
  ["被窝里的十分钟，是冬天的小确幸 ❄️","Ten extra minutes in bed is winter's small joy"],
  ["昨晚睡得好，今天走路都带风","Slept great last night, now I walk with bounce"],
  ["睡前读几页书，让心慢慢静下来 📖","A few pages before bed slowly calm my mind"],
  ["今天也要抽空读点喜欢的文字","Make time today for words I love"],
  ["一本好书，是随手就能去的远方 🌍","A good book is a journey within reach"],
  ["读到好句子，忍不住抄进小本子里","Great lines get copied into my little notebook"],
  ["泡杯热茶配本书，下午就很完美 🍵","Hot tea plus a book makes a perfect afternoon"],
  ["读不进去就换一本，读书不该是任务","Switch books if bored; reading isn't homework"],
  ["书页翻动的声音，比白噪音还治愈 📚","Turning pages soothes me more than white noise"],
  ["这个月的目标是读完那本买了很久的书","This month's goal: finish that long-bought book"],
  ["在地铁上读书，拥挤都变得可爱了","Reading on the subway makes crowds bearable"],
  ["好书值得读两遍，第二遍更懂自己","Good books deserve rereads; the second teaches more"],
  ["今天读到一句话，突然就想通了 💡","One sentence today suddenly made everything click"],
  ["床头放本书，梦都会变得有故事","A book on the nightstand makes dreams richer"],
  ["戴上耳机，世界就剩我和这首歌 🎧","Headphones on, just me and this song"],
  ["单曲循环一整天，也不觉得腻 🔂","Looping one song all day without tiring"],
  ["心情不好时，让音乐替我消化 🎵","Bad moods get digested by music"],
  ["洗澡唱歌不跑调，算我超常发挥","Singing on-key in the shower is my peak"],
  ["随机播放到老歌，像遇见老朋友 🎶","Shuffle plays an old song like meeting an old friend"],
  ["边听歌边走路，步伐都自带节奏","Walking with music gives my steps their own beat"],
  ["深夜的歌单，要温柔一点 🌃","Late-night playlists should stay gentle"],
  ["把喜欢的歌分享给朋友，快乐会翻倍","Sharing favorite songs doubles the joy"],
  ["做家务配点音乐，琐碎也变得有趣","Chores with music turn dull tasks fun"],
  ["下雨天的标配：热咖啡和慢歌 ☕","Rainy day essentials: hot coffee and slow songs"],
  ["整理房间，顺便整理了心情 🧺","Tidying my room tidies my mood too"],
  ["桌面干净了，思路也跟着清爽","A clean desk brings a clear mind"],
  ["断舍离一小时，房间会呼吸了 🌬️","An hour of decluttering lets the room breathe"],
  ["叠好被子再出门，仪式感拉满","Making the bed first sets the day's tone"],
  ["把旧照片翻出来擦擦，回忆亮晶晶","Dusting off old photos makes memories shine"],
  ["扔掉不用的东西，心里也轻了不少","Tossing unused stuff lightens my heart"],
  ["给绿植浇浇水，房间就有了生气 🪴","Watering my plants brings the room alive"],
  ["周末大扫除，流汗也很快乐","Weekend deep cleaning, sweaty but happy"],
  ["收纳盒贴上标签，找东西不再抓狂 🏷️","Labeled boxes end my frantic searching"],
  ["换上干净的床单，今晚睡得格外香","Fresh sheets promise extra sweet sleep tonight"],
  ["发会儿呆不是浪费，是给大脑放个假 ☁️","Zoning out isn't waste; it's a brain vacation"],
  ["看云从窗前飘过，时间慢得刚刚好","Clouds drift by, time slows just right"],
  ["什么都不做的一个小时，也很珍贵","An hour of doing nothing is precious too"],
  ["盯着咖啡冒热气，发呆也是正经事 ☕","Watching coffee steam counts as serious business"],
  ["阳光晒在背上，暖得不想动弹 🌞","Sun on my back, too cozy to move"],
  ["偶尔的放空，是为了更好地出发","Occasional blank time fuels a better restart"],
  ["路边的小花开了，忍不住多看两眼 🌸","Roadside flowers bloom, worth a second look"],
  ["吃到好吃的早餐，一天都有了盼头","A tasty breakfast gives the day purpose"],
  ["喝到第一口热汤，整个人都暖了 🍲","First sip of hot soup warms me completely"],
  ["下班路上的晚霞，是免费的礼物 🌇","The sunset on my commute is a free gift"],
  ["雨声敲着窗户，适合窝着不动 🌧️","Rain on the window means stay cozy inside"],
  ["猫猫在脚边打呼，幸福就这么简单","A purring cat at my feet, happiness this simple"],
  ["新袜子软乎乎的，走路都开心 🧦","Soft new socks make every step happy"],
  ["闻到刚出炉的面包香，脚步就停下了 🍞","Fresh bread smell stops me mid-stride"],
  ["给自己买束花，普通日子也发光 💐","Buying myself flowers makes ordinary days glow"],
  ["这个周末不安排，就是最好的安排","An unplanned weekend is the best plan"],
  ["周五晚上列清单，周末快乐不打折 📝","Friday night list-making doubles weekend fun"],
  ["周末去公园走走，把阳光存进身体","Weekend park walks store sunshine in me"],
  ["睡到自然醒再出门，周末就该这样","Sleep in, then head out; weekends done right"],
  ["计划赶不上懒觉，那就随心过吧 😆","Plans lose to lie-ins; just go with the flow"],
  ["周末骑车兜风，风把烦恼都吹走了 🚲","Weekend bike rides blow worries away"],
  ["给自己做顿大餐，周末要有烟火气","Cooking a feast gives weekends soul"],
  ["去逛菜市场，热热闹闹才是生活 🥬","Bustling markets are what living looks like"],
  ["周末看场老电影，和过去碰个杯 🎬","Weekend old movies, a toast to the past"],
  ["出门走走吧，好天气不该被浪费 ☀️","Get outside; good weather shouldn't be wasted"],
  ["周日晚上早点睡，给周一留点元气","Early sleep Sunday saves energy for Monday"],
  ["周末约饭不如约散步，边走边聊更好","Skip dinner dates; walk-and-talk is better"],
  ["留半天给自己，谁都别想约走 🙅","Half a day for myself, no invitations allowed"],
  ["周末去图书馆泡一下午，安静又充实","A library afternoon, quiet yet fulfilling"],
  ["把周末过成喜欢的样子，不算奢侈","Living weekends my way isn't a luxury"],
  ["和老朋友煲电话粥，一聊就是两小时 📞","Two-hour calls with old friends fly by"],
  ["有些废话，只能说给懂的人听 💬","Some nonsense only true friends deserve"],
  ["朋友突然的问候，比奶茶还甜 🧋","A friend's surprise hello beats sweet milk tea"],
  ["约好了周末见面，从现在开始期待","Weekend meetup planned; I'm counting down already"],
  ["群聊里的哈哈哈，是打工人的续命水 😂","Group chat laughter keeps us workers alive"],
  ["和朋友吐槽完，烦恼少了一半","Venting to friends halves my troubles"],
  ["好久不见，一见面还是老样子 🤗","Long time no see, same old us"],
  ["分享欲被接住的感觉，真好","Having my sharing caught feels wonderful"],
  ["深夜和闺蜜聊天，越聊越精神 🌙","Late-night chats with my bestie beat coffee"],
  ["朋友的生日要记得，蛋糕也要吃双份 🎂","Remember their birthday, eat double cake"],
  ["一起发呆的朋友，最难得","Friends who zone out together are rare gems"],
  ["把今天的趣事讲给朋友，快乐翻了倍","Telling friends today's fun doubles the joy"],
  ["隔着屏幕的晚安，也是真的温暖 🌟","A goodnight through the screen still warms"],
  ["老友相聚不用菜多，话够就行","Old friends need no feast, just conversation"],
  ["谢谢那个随时听我唠叨的人 ❤️","Thank you, whoever always hears me ramble"]
];

const ALMANAC_YI = [
  ["吃火锅","Have hotpot"],
  ["散步","Take a walk"],
  ["看云","Watch the clouds"],
  ["喝奶茶","Grab milk tea"],
  ["读书","Read a book"],
  ["早睡","Sleep early"],
  ["晒太阳","Bask in the sun"],
  ["写日记","Journal"],
  ["吃水果","Eat fruit"],
  ["听歌","Listen to music"],
  ["整理房间","Tidy the room"],
  ["和朋友聊天","Chat with friends"],
  ["发呆","Zone out"],
  ["拍照","Take photos"],
  ["做运动","Exercise"],
  ["下厨","Cook a meal"],
  ["撸猫","Pet a cat"],
  ["打游戏","Play games"],
  ["逛公园","Visit a park"],
  ["记录生活","Record life"]
];

const ALMANAC_JI = [
  ["熬夜","Staying up late"],
  ["拖延","Procrastinating"],
  ["暴饮暴食","Overeating"],
  ["久坐","Sitting all day"],
  ["乱花钱","Impulse spending"],
  ["空腹喝咖啡","Coffee on an empty stomach"],
  ["深夜刷手机","Late-night scrolling"],
  ["赖床到中午","Sleeping till noon"],
  ["生闷气","Sulking"],
  ["忘喝水","Forgetting to drink water"],
  ["想太多","Overthinking"],
  ["宅一整天","Staying in all day"],
  ["饿着睡觉","Sleeping hungry"],
  ["吃太撑","Eating too much"]
];
